# Generated by Django 4.2.2 on 2023-07-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecategory',
            name='acronym',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='fee_type',
            field=models.CharField(choices=[('M', 'Mandatory'), ('R', 'Recursive'), ('O', 'Optional')], max_length=1),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
