# Generated by Django 4.2.2 on 2023-07-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_feecategory_acronym_alter_feecategory_fee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecategory',
            name='fee_type',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Recursive', 'Recursive'), ('Optional', 'Optional')], max_length=250),
        ),
    ]
